---

- name: Creating Consul Serivce
  template:
    src: service.j2
    dest: /etc/systemd/system/consul.service

- name: Starting Consul Service
  systemd:
    name: consul
    state: started
    enabled: true
    daemon_reload: true
